# Introduction to NumPy and Review of Linear Algebra

Numpy is a library for Python that allows us to caryoug computations of large, multi-dimensional arrays. It contains lots of mathematical functions that are useful for operating on arrays.

In [5]:
# Import the library
import numpy as np

# Scalars

Theses are just single numbers denoted by lower case constants. In this course we mostly assume real numbers

$$ a, b, c, d \in \mathbb{R} $$

## Vectors

Vectors are 1-D arrays of scalars denoted by bold face lowercase letters

$$ \mathbf{x} = \left[\begin{array}{@{}c@{}}
    a \\
    b \\
    c 
    \end{array} \right] $$
    
We think of vectors as identifying a point in n-dimensional space.

$$ \mathbf{x} \in \mathbb{R}^n $$

In [6]:
# Creating vectors in NumPy:

# Row vectors:
ROW = np.array([3, 6, 7, 2])

# Column vectors:
COL = np.array([[3],[6],[7],[2]])

print("Row vector:\n", ROW, "\nColumn vector:\n", COL)

Row vector:
 [3 6 7 2] 
Column vector:
 [[3]
 [6]
 [7]
 [2]]


## Matrix

A matrix is a 2-D array of numbers denoted by bold face uppercase letters

$$ \mathbf{A} = \left[\begin{array}{@{}c,c@{}}
    a & b \\
    c & d
    \end{array} \right] $$
    
In general, a matrix does not have to be square:

$$ \mathbf{A} \in \mathbb{R}^{m\times n} $$


In [7]:
# Creating a matrix in Numpy:

MAT = np.array([[3,6,7,2],[1,2,3,4]])
print("This is a 2 by 4 matrix:\n", MAT)

This is a 2 by 4 matrix:
 [[3 6 7 2]
 [1 2 3 4]]


## Selecting Elements in a Vector or Matrix

We defined ROW, COL, and MAT above. Let's interact with these things!

In [8]:
print('ROW:\n', ROW)
print('COL:\n', COL)
print('MAT:\n', MAT)

ROW:
 [3 6 7 2]
COL:
 [[3]
 [6]
 [7]
 [2]]
MAT:
 [[3 6 7 2]
 [1 2 3 4]]


In [9]:
# Element of a vector
print(ROW[1])

6


In [10]:
# Element of a matrix
print(MAT[1,1])

2


In [11]:
# All elements of a vector
print(COL[:])

[[3]
 [6]
 [7]
 [2]]


In [12]:
# First three elements of a vector
print(COL[:3])

[[3]
 [6]
 [7]]


Here : 3 means up to and including the third element

In [13]:
# Everything after element 2 in the vector
print(ROW[2:])

[7 2]


It is important to keep track of both the size and the shape of the outputs!!

In [14]:
# First rows and all columns of the matrix
print(MAT[:1,:])

[[3 6 7 2]]


In [15]:
# What will the following command do?
print(MAT[:,COL[-1]])

[[7]
 [3]]


In [16]:
# What will the following command do?
print(MAT[-1,1:3])

[2 3]


## Learning about a matrix

Sometimes you need to access the dimensions of the matrix. There are quick commands for this!

In [17]:
# See the size of a matrix: (rows, columns)
SIZE = MAT.shape
print(SIZE) #rows,columns

(2, 4)


In [18]:
# See the number of elements
print(MAT.size)

8


In [19]:
# See the number of dimensions
print(MAT.ndim)

2


## Tensors

Tensors are a revtangular grid of numbers that are allowed to have a variable numnber of axis. For example a 3-D matrix is a tensor who's elements would be 

$$ A_{i,j,k} $$

In [20]:
# Define a tensor
MAT2 = np.array([[30,60,70,20],[10,20,30,40]])
TENS = np.array([MAT, MAT2])
print(TENS.ndim)

3


In [21]:
# You can access the elements in a similar way
print(TENS)
print('The element in the first row, third column, second layer is:\n', TENS[1,0,2]) #layer,row,column

# Here the order goes TENS[layer_num, row, col]

[[[ 3  6  7  2]
  [ 1  2  3  4]]

 [[30 60 70 20]
  [10 20 30 40]]]
The element in the first row, third column, second layer is:
 70


## Matrix Operations:

- element operations
- max and min values
- statistics
- transpose
- rehape
- addition
- multiplication
- inverse and linear systems
- norms
- eigenvalues
- extra

<h3> Element Operations </h3>

In [22]:
# To apply an operation to multiple elements in an array you need np.vectorize
print(MAT)

# Create a function that does something
add_20 = lambda i: i+20

# Then vectorize it
vec_add_20 = np.vectorize(add_20)

# Finally use the function on the matrix
print('Hey look! We added 20:\n', vec_add_20(MAT))

[[3 6 7 2]
 [1 2 3 4]]
Hey look! We added 20:
 [[23 26 27 22]
 [21 22 23 24]]


<h3> Max and Min </h3>

In [23]:
# Finding the Max and Min Values Overall
print(np.max(MAT))
print(np.min(MAT))

7
1


In [24]:
# Finding the Max and Min Values for each

# Column
print(np.max(MAT,axis=0))

# Row
print(np.max(MAT,axis=1))

[3 6 7 4]
[7 4]


<h3> Statistics </h3>

In [25]:
# Some helpful Statistical tools

# Average
print(np.mean(MAT))
print(np.mean(MAT,axis=1))

# Standard Dev
print(np.std(MAT))

# Variance
print(np.var(MAT))

# Covariance
print(np.cov(MAT))

3.5
[4.5 2.5]
1.9364916731037085
3.75
[[ 5.66666667 -0.33333333]
 [-0.33333333  1.66666667]]


In [26]:
# Although pandas is probably better for some of this stuff!
import pandas as pd

# Statistics along the columns
PDMAT1 = pd.DataFrame(MAT)
print(PDMAT1.describe())

# Statistics along the rows
PDMAT2 = pd.DataFrame(MAT.T)
print(PDMAT2.describe())

              0         1         2         3
count  2.000000  2.000000  2.000000  2.000000
mean   2.000000  4.000000  5.000000  3.000000
std    1.414214  2.828427  2.828427  1.414214
min    1.000000  2.000000  3.000000  2.000000
25%    1.500000  3.000000  4.000000  2.500000
50%    2.000000  4.000000  5.000000  3.000000
75%    2.500000  5.000000  6.000000  3.500000
max    3.000000  6.000000  7.000000  4.000000
              0         1
count  4.000000  4.000000
mean   4.500000  2.500000
std    2.380476  1.290994
min    2.000000  1.000000
25%    2.750000  1.750000
50%    4.500000  2.500000
75%    6.250000  3.250000
max    7.000000  4.000000


<h3> Transpose </h3>

In [27]:
# Matrix transpose - exchanges the rows and columns
print(MAT.T)

[[3 1]
 [6 2]
 [7 3]
 [2 4]]


<h3> Reshape </h3>

In [28]:
# Sometimes we need to reshape our data so that operations work properly

# Reshape this so that it is a column vector
print(MAT.reshape(MAT.size,1))

# Or we could do it this way
print(MAT.reshape(-1,1)) # the -1 says to use an many rows as needed

[[3]
 [6]
 [7]
 [2]
 [1]
 [2]
 [3]
 [4]]
[[3]
 [6]
 [7]
 [2]
 [1]
 [2]
 [3]
 [4]]


<h3> Addition, subtraction, and multiplication </h3>

In [29]:
# Matrix addition, subtraction, and multiplication

# NOTE: Here the size of the matrix is important. Dimensions must match. If they don't match you will get errors like:
# "operands could not be broadcast together with shapes ( ) ( )"

# Recall our previously stored vectors and matrices
print('ROW:\n', ROW)
print('COL:\n', COL)
print('MAT:\n', MAT)
print('MAT2:\n', MAT2)

ROW:
 [3 6 7 2]
COL:
 [[3]
 [6]
 [7]
 [2]]
MAT:
 [[3 6 7 2]
 [1 2 3 4]]
MAT2:
 [[30 60 70 20]
 [10 20 30 40]]


In [30]:
# Add
print(np.add(MAT, MAT2))

# Subtract
print(np.subtract(MAT,MAT2))

# Hadmard Product - Element Wise
print(MAT*MAT2)

[[33 66 77 22]
 [11 22 33 44]]
[[-27 -54 -63 -18]
 [ -9 -18 -27 -36]]
[[ 90 360 490  40]
 [ 10  40  90 160]]


In [31]:
# Matrix Multiplication
print(np.matmul(MAT,MAT2.T))

[[980 440]
 [440 300]]


In [32]:
# Vector dot products
print(np.dot(ROW,COL))
print(ROW @ COL)

[98]
[98]


In [33]:
# BEWARE OF BROADCASTING - applies to the + COL to each column in MAT
print(MAT.T+COL)

[[ 6  4]
 [12  8]
 [14 10]
 [ 4  6]]


In [35]:
# What will this do?
print(MAT.T*COL)
print(MAT.T)
print(COL)

[[ 9  3]
 [36 12]
 [49 21]
 [ 4  8]]
[[3 1]
 [6 2]
 [7 3]
 [2 4]]
[[3]
 [6]
 [7]
 [2]]


<h3> Inverse and Linear Systems </h3>

In [30]:
# When solving a linear system Ax=b you sometimes need the matrix inverse
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,2,3])

# The solution is given by x = A^(-1)b
Ainv = np.linalg.inv(A)
print(Ainv)

x = np.matmul(Ainv,b)
print(x)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
[ 4. -4.  2.]


<h3> Vector and Matrix Norms </h3>

In [31]:
# Often times we want to understand something about the size of a vector.
# NORMS help us do this

# ALL OF THESE assume input is a vector
# L^2 Norm = Euclidian norm 
Ltwo = np.linalg.norm(ROW)
print(Ltwo)

# L^1 Norm - best when considering points near zero, good at telling zeros from epsilons
Lone = np.linalg.norm(ROW,1)
print(Lone)

# L^invinity Norm = max norm - tells the maximum distance
Linf = np.linalg.norm(ROW,np.inf)
print(Linf)


9.899494936611665
18.0
7.0


In [32]:
# We can also calculate the "size" of a matrix using the frobenius norm (most common in ML)
Mfro = np.linalg.norm(MAT)
print(Mfro)

11.313708498984761


<h3> Eigenvalues and Eigenvectors </h3>

Given a linear transformation represented by a matrix A, eigenvectors are a special set of vectors in the space such that when A is applied they change only in scale and not direction.

$$ \mathbf{A}\mathbf{v} = \lambda \mathbf{v} $$

In [33]:
# Eigenvalues and eivenvectors are helpful in many applied mathematics settings 

# Using the A matrix defined above
print(A)

# Calculate the E-vals and E-vects
lam,v = np.linalg.eig(A)
print(lam)
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


<h3> Other fun things </h3>

In [34]:
# Generating random variables

# A random scalar between 1 and 99
r = np.random.randint(0,100)
print(r)

# A few random scalars between 1 and 99
print(np.random.randint(0,100,4))

42
[44 88 36 92]
